### ISSUE TITLE
Slowness problems

### ISSUE THREAD

**Issue by rodrigoKulb** [danba340/minecraft-react#1]
Congratulations. I noticed 2 problems with slowness, the first after creating a large amount of boxes, it starts to slow down to create new ones.
The second is the auto saveWord is also slow I ended up commenting it

**Comment by rodrigoKulb** [comment]
I found this project on git https://github.com/satansdeer/minecraft-react, it has a good speed, but less functionality. Is "localStorage" slowing down?

**Comment by rodrigoKulb** [comment]
I removed the localStorage system that uses HD to save the cubes, it was much faster

**Comment by rodrigoKulb** [comment]
I put an analysis of the FPS and when I put more than 40 cubes, the FPS when I add new ones drops to 3, can we optimize "Saving the old cubes" or something?
![Captura de tela em 2021-01-17 17-49-57](https://user-images.githubusercontent.com/5334261/104855664-c4126c80-58ec-11eb-9e98-50deeb531b2d.png)

**Comment by danba340** [comment]
Thanks for investigating :) Its weird that a simple save to LocalStorage would slow it down that much, and only every 10 seconds. 
My guess is that every cube has to rerender when one is added. I have moved the key={nanoid()} to happen in the store rather than in the render. That should fix that problem maybe?

**Comment by rodrigoKulb** [comment]
Yes the problem is when you add a new cube it renders everything again. Ideal is to move an already created cube or add the cube without rendering them all again. It would be possible?

**Comment by danba340** [comment]
I have it running smoothly with 400 cubes now :)

**Comment by rodrigoKulb** [comment]
Have you published version? I'll try.

**Comment by danba340** [comment]
Sure i will push it as soon as im done :)

**Comment by danba340** [comment]
Pushed

**Comment by rodrigoKulb** [comment]
Perfect! I tested it and it was amazing
