### ISSUE TITLE
Problem with Ground Redraw

### ISSUE THREAD

**Issue by heyflynn** [danba340/minecraft-react#2]
Hey. I tried the tutorial this weekend and thought it was great!

I found a few issues with how you're using three in React. 

For starters,  in the Ground component, the texture is loading for every ground click event. This is because of how functional components manage state. When you addCube, the entire component will render again and loading the texture each click.

to fix create an init function to intitalize and pass it as the param in useState

```
function initGround() {
    const t = new TextureLoader().load(grass)
    t.wrapS = RepeatWrapping
    t.wrapT = RepeatWrapping
    t.repeat.set(100, 100)
    return t
}

export const Ground = memo((props) => {
    const [ref] = usePlane(() => ({ rotation: [-Math.PI / 2, 0, 0], ...props }))
    const [texture, setGroundTexture] = useState(initGround())

```

That will stop the texture from loading and redrawing the entire scene with each click.

**Comment by heyflynn** [comment]
It was still loading the grass block after each click so I moved the entire initGround into useMemo and it stopped loading the grass block on click.

```
    const texture = useMemo(() => {
        const t = new TextureLoader().load(grass)
        t.wrapS = RepeatWrapping
        t.wrapT = RepeatWrapping
        t.repeat.set(100, 100)
        return t
    }, [])
```

**Comment by danba340** [comment]
Very cool! Thanks Flynn!

**Comment by danba340** [comment]
Merged
