### ISSUE TITLE
Very slow on large buildings

### ISSUE THREAD

**Issue by rodrigoKulb** [danba340/minecraft-react#4]
Great Daniel,

I'm creating a project where you can save the maps on the server, but I found a performance problem even after the changes you made. If you access the link:
https://minecraft-react-game-k4dqc5eq4-rodrigokulb.vercel.app/ 

Click on "Abrir Mapa (Open Map)" => "Casa Rodrigo Kulb" you will see how slow it has become. 

I found another project in threejs with less functions but apparently much faster.
http://ubershmekel.github.io/mine3js/ Can we improve performance on large maps?

**Comment by rodrigoKulb** [comment]
I deduced all textures to 16 x 16 pixels but still have a lot of FPS lag

**Comment by rodrigoKulb** [comment]
I found the possible problem, when in the Cube.js file, when you separate into faces by placing the {[... Array (6)] .map each object turns into 6 objects, 100 cubes become 600 faces. I made a modification to the file as below and got an excellent performance:

**Current part**
`{[...Array(6)].map((_, index) => (
<meshStandardMaterial
  //attachArray="material"
  map={textures['dirt']}
  key={index}
  color={hover === index ? 'gray' : 'green'}
  opacity={texture === 'glass' ? 0.7 : 1}
  //color={'green'}
  transparent={true}
/>
))}`

**After modification**
` <boxBufferGeometry attach="geometry" />
 <meshStandardMaterial 
 attach="material"  
 map={textures[texture]} 
 color={hover ? 'gray' : color}
 opacity={texture === 'glass' ? 0.7 : 1}
 transparent={true}
 />`

**Comment by danba340** [comment]
Thats so awesome rodrigo!! :D

Im happy to merge in your change :)

**Comment by danba340** [comment]
Change added to project. Mentioned you in commit message

**Comment by rodrigoKulb** [comment]
Hi Daniel,

Thank you very much for Mentioned in the project, I found another bug after this change when the face is equal to 0 the hover is not working, I had to make a change.

Current part
`<boxBufferGeometry attach="geometry" /> <meshStandardMaterial attach="material" map={textures[texture]} color={hover ? 'gray' : color} opacity={texture === 'glass' ? 0.7 : 1} transparent={true} />`

After modification
`<boxBufferGeometry attach="geometry" />
 <meshStandardMaterial 
 attach="material"  
 map={textures[texture]} 
 color={hover!=null ? 'gray' : color}
 opacity={texture === 'glass' ? 0.7 : 1}
 transparent={true}
 />`
