### ISSUE TITLE
I found another bug after this change

### ISSUE THREAD

**Issue by rodrigoKulb** [danba340/minecraft-react#5]
Hi Daniel,

Thank you very much for Mentioned in the project, I found another bug after this change when the face is equal to 0 the hover is not working, I had to make a change.

**Current part**
`<boxBufferGeometry attach="geometry" /> <meshStandardMaterial attach="material" map={textures[texture]} color={hover ? 'gray' : color} opacity={texture === 'glass' ? 0.7 : 1} transparent={true} />`

**After modification**
`<boxBufferGeometry attach="geometry" />
<meshStandardMaterial 
attach="material"  
map={textures[texture]} 
color={hover!=null ? 'gray' : color}
opacity={texture === 'glass' ? 0.7 : 1}
transparent={true}
/>`

**Comment by danba340** [comment]
Code updated 👍
